// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;


function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith('sb_publishable_') || value.startsWith('sb_secret_');
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== 'undefined' && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (isNewSupabaseApiKey(supabaseKey) && headers.get('Authorization') === `Bearer ${supabaseKey}`) {
      headers.delete('Authorization');
    }

    headers.set('apikey', supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

// "Ricordami" al login: se non selezionato, la sessione va in sessionStorage
// (sparisce alla chiusura del browser) invece che in localStorage
// (sopravvive). auth.ts imposta questo flag prima di ogni signIn/signUp.
const REMEMBER_SESSION_KEY = "navta.remember_me";

function getSessionStorage(): Storage {
  return localStorage.getItem(REMEMBER_SESSION_KEY) === "false" ? sessionStorage : localStorage;
}

export const authStorage = {
  getItem: (key: string) => getSessionStorage().getItem(key),
  setItem: (key: string, value: string) => getSessionStorage().setItem(key, value),
  removeItem: (key: string) => getSessionStorage().removeItem(key),
};

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  global: {
    fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY),
  },
  auth: {
    storage: authStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
